
import os
import re
import logging
import asyncio
import random
from datetime import datetime, timedelta

from sqlalchemy import create_engine, text
from sqlalchemy.exc import IntegrityError

from telegram import Update
from telegram.error import BadRequest, Forbidden, RetryAfter, TelegramError
from telegram.ext import (
    Application,
    ApplicationBuilder,
    CommandHandler,
    ContextTypes,
)

TOKEN = os.environ["BOT_TOKEN"]

ADMIN_IDS = {
    int(x.strip())
    for x in os.environ.get("ADMIN_IDS", "").split(",")
    if x.strip().isdigit()
}

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
SQLITE_PATH = os.environ.get("DB_PATH", "relay_bot.db")

SEND_INTERVAL_SECONDS = int(os.environ.get("SEND_INTERVAL_SECONDS", "3600"))
MIN_SEND_DELAY = float(os.environ.get("MIN_SEND_DELAY", "1.2"))
MAX_SEND_DELAY = float(os.environ.get("MAX_SEND_DELAY", "2.0"))
RETRY_EXTRA_SECONDS = float(os.environ.get("RETRY_EXTRA_SECONDS", "1.0"))

logging.basicConfig(
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger("relay-bot")

SEND_LOCK = asyncio.Lock()

# Railway/Render PostgreSQL이 있으면 그걸 우선 사용.
# 없으면 로컬 SQLite로 자동 fallback.
if DATABASE_URL:
    # 일부 서비스가 postgres:// 형식을 줄 수 있어 SQLAlchemy 호환형으로 보정
    if DATABASE_URL.startswith("postgres://"):
        DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql+psycopg://", 1)
    elif DATABASE_URL.startswith("postgresql://"):
        DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+psycopg://", 1)

    engine = create_engine(
        DATABASE_URL,
        pool_pre_ping=True,
        pool_recycle=300,
    )
    DB_KIND = "PostgreSQL"
else:
    engine = create_engine(
        f"sqlite:///{SQLITE_PATH}",
        connect_args={"check_same_thread": False},
    )
    DB_KIND = "SQLite"


def init_db():
    with engine.begin() as conn:
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS target_groups (
                chat_id BIGINT PRIMARY KEY,
                title TEXT,
                added_at TEXT NOT NULL,
                enabled INTEGER NOT NULL DEFAULT 1
            )
        """))

        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS source_posts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_chat TEXT NOT NULL,
                message_id BIGINT NOT NULL,
                original_link TEXT NOT NULL UNIQUE,
                added_at TEXT NOT NULL,
                enabled INTEGER NOT NULL DEFAULT 1
            )
        """) if DB_KIND == "PostgreSQL" else text("""
            CREATE TABLE IF NOT EXISTS source_posts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                source_chat TEXT NOT NULL,
                message_id INTEGER NOT NULL,
                original_link TEXT NOT NULL UNIQUE,
                added_at TEXT NOT NULL,
                enabled INTEGER NOT NULL DEFAULT 1
            )
        """))

        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS settings (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            )
        """))

        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS send_logs (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                group_id BIGINT,
                post_id BIGINT,
                status TEXT NOT NULL,
                error_text TEXT,
                created_at TEXT NOT NULL
            )
        """) if DB_KIND == "PostgreSQL" else text("""
            CREATE TABLE IF NOT EXISTS send_logs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                group_id INTEGER,
                post_id INTEGER,
                status TEXT NOT NULL,
                error_text TEXT,
                created_at TEXT NOT NULL
            )
        """))

        existing = conn.execute(
            text("SELECT value FROM settings WHERE key = :key"),
            {"key": "enabled"},
        ).fetchone()

        if not existing:
            conn.execute(
                text("INSERT INTO settings(key, value) VALUES(:key, :value)"),
                {"key": "enabled", "value": "1"},
            )


def is_admin(update: Update) -> bool:
    user = update.effective_user
    return bool(user and user.id in ADMIN_IDS)


async def admin_guard(update: Update) -> bool:
    if is_admin(update):
        return True
    if update.effective_message:
        await update.effective_message.reply_text("관리자만 사용할 수 있습니다.")
    return False


def parse_telegram_post_link(link: str):
    link = link.strip()

    m = re.match(
        r"^https?://(?:t\.me|telegram\.me)/c/(\d+)/(\d+)(?:\?.*)?$",
        link,
        re.IGNORECASE,
    )
    if m:
        return int("-100" + m.group(1)), int(m.group(2))

    m = re.match(
        r"^https?://(?:t\.me|telegram\.me)/([A-Za-z0-9_]+)/(\d+)(?:\?.*)?$",
        link,
        re.IGNORECASE,
    )
    if m:
        return f"@{m.group(1)}", int(m.group(2))

    raise ValueError("지원하지 않는 텔레그램 게시물 링크입니다.")


def retry_seconds(value) -> float:
    if isinstance(value, timedelta):
        return max(value.total_seconds(), 1.0)
    try:
        return max(float(value), 1.0)
    except Exception:
        return 5.0


def log_send(group_id, post_id, status, error_text=None):
    try:
        with engine.begin() as conn:
            conn.execute(
                text("""
                    INSERT INTO send_logs(
                        group_id, post_id, status, error_text, created_at
                    )
                    VALUES(
                        :group_id, :post_id, :status, :error_text, :created_at
                    )
                """),
                {
                    "group_id": group_id,
                    "post_id": post_id,
                    "status": status,
                    "error_text": error_text,
                    "created_at": datetime.now().isoformat(timespec="seconds"),
                },
            )
    except Exception:
        logger.exception("발송 로그 저장 실패")


async def cmd_help(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    await update.effective_message.reply_text(
        "📢 채널 → 여러 그룹 자동 발송 봇\n\n"
        "관리자 개인채팅:\n"
        "/등록 <게시물링크>\n"
        "/삭제 <번호>\n"
        "/등록목록\n"
        "/즉시발송\n"
        "/자동시작\n"
        "/자동중지\n"
        "/상태\n"
        "/최근로그\n\n"
        "발송받을 그룹:\n"
        "/방등록\n"
        "/방삭제\n"
        "/방목록\n\n"
        "예시:\n"
        "/등록 https://t.me/channelname/152"
    )


async def cmd_add_group(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    chat = update.effective_chat
    if not chat or chat.type not in ("group", "supergroup"):
        await update.effective_message.reply_text(
            "이 명령어는 발송받을 그룹 안에서 사용해주세요."
        )
        return

    title = chat.title or str(chat.id)
    now = datetime.now().isoformat(timespec="seconds")

    with engine.begin() as conn:
        row = conn.execute(
            text("SELECT chat_id FROM target_groups WHERE chat_id = :chat_id"),
            {"chat_id": chat.id},
        ).fetchone()

        if row:
            conn.execute(
                text("""
                    UPDATE target_groups
                    SET title = :title, enabled = 1
                    WHERE chat_id = :chat_id
                """),
                {"title": title, "chat_id": chat.id},
            )
        else:
            conn.execute(
                text("""
                    INSERT INTO target_groups(chat_id, title, added_at, enabled)
                    VALUES(:chat_id, :title, :added_at, 1)
                """),
                {"chat_id": chat.id, "title": title, "added_at": now},
            )

    await update.effective_message.reply_text(
        f"✅ 발송 그룹 등록 완료\n{title}\nID: {chat.id}"
    )


async def cmd_remove_group(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    chat = update.effective_chat
    if not chat or chat.type not in ("group", "supergroup"):
        await update.effective_message.reply_text(
            "삭제할 그룹 안에서 /방삭제 를 입력해주세요."
        )
        return

    with engine.begin() as conn:
        result = conn.execute(
            text("DELETE FROM target_groups WHERE chat_id = :chat_id"),
            {"chat_id": chat.id},
        )

    if result.rowcount:
        await update.effective_message.reply_text(
            "✅ 이 그룹을 발송 목록에서 삭제했습니다."
        )
    else:
        await update.effective_message.reply_text(
            "등록되어 있지 않은 그룹입니다."
        )


async def cmd_group_list(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    with engine.begin() as conn:
        rows = conn.execute(
            text("""
                SELECT chat_id, title
                FROM target_groups
                WHERE enabled = 1
                ORDER BY added_at ASC
            """)
        ).mappings().all()

    if not rows:
        await update.effective_message.reply_text("등록된 발송 그룹이 없습니다.")
        return

    lines = [f"📋 등록된 발송 그룹 ({len(rows)}개)"]
    for i, row in enumerate(rows, 1):
        lines.append(f"{i}. {row['title']} ({row['chat_id']})")

    chunk = ""
    for line in lines:
        if len(chunk) + len(line) + 1 > 3500:
            await update.effective_message.reply_text(chunk)
            chunk = ""
        chunk += line + "\n"

    if chunk:
        await update.effective_message.reply_text(chunk)


async def cmd_add_post(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    if not context.args:
        await update.effective_message.reply_text(
            "사용법: /등록 https://t.me/channelname/152"
        )
        return

    link = context.args[0].strip()

    try:
        source_chat, message_id = parse_telegram_post_link(link)
    except ValueError as e:
        await update.effective_message.reply_text(f"❌ {e}")
        return

    now = datetime.now().isoformat(timespec="seconds")

    try:
        with engine.begin() as conn:
            conn.execute(
                text("""
                    INSERT INTO source_posts(
                        source_chat, message_id, original_link, added_at, enabled
                    )
                    VALUES(
                        :source_chat, :message_id, :original_link, :added_at, 1
                    )
                """),
                {
                    "source_chat": str(source_chat),
                    "message_id": message_id,
                    "original_link": link,
                    "added_at": now,
                },
            )

            row = conn.execute(
                text("""
                    SELECT id
                    FROM source_posts
                    WHERE original_link = :original_link
                """),
                {"original_link": link},
            ).fetchone()

            post_id = row[0]

    except IntegrityError:
        await update.effective_message.reply_text("이미 등록된 게시물입니다.")
        return

    await update.effective_message.reply_text(
        f"✅ 게시물 등록 완료\n"
        f"번호: {post_id}\n"
        f"원본: {link}\n\n"
        f"/즉시발송 으로 테스트할 수 있습니다."
    )


async def cmd_remove_post(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    if not context.args or not context.args[0].isdigit():
        await update.effective_message.reply_text("사용법: /삭제 <등록번호>")
        return

    post_id = int(context.args[0])

    with engine.begin() as conn:
        result = conn.execute(
            text("DELETE FROM source_posts WHERE id = :id"),
            {"id": post_id},
        )

    if result.rowcount:
        await update.effective_message.reply_text(
            f"✅ 게시물 {post_id}번 삭제 완료"
        )
    else:
        await update.effective_message.reply_text(
            "해당 번호의 게시물이 없습니다."
        )


async def cmd_post_list(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    with engine.begin() as conn:
        rows = conn.execute(
            text("""
                SELECT id, original_link, enabled
                FROM source_posts
                ORDER BY id ASC
            """)
        ).mappings().all()

    if not rows:
        await update.effective_message.reply_text("등록된 게시물이 없습니다.")
        return

    lines = ["📌 등록된 자동 발송 게시물"]
    for row in rows:
        state = "ON" if row["enabled"] else "OFF"
        lines.append(f"{row['id']}. [{state}] {row['original_link']}")

    await update.effective_message.reply_text("\n".join(lines))


def automatic_enabled() -> bool:
    with engine.begin() as conn:
        row = conn.execute(
            text("SELECT value FROM settings WHERE key = :key"),
            {"key": "enabled"},
        ).fetchone()

    return bool(row and row[0] == "1")


def set_automatic(enabled: bool):
    value = "1" if enabled else "0"

    with engine.begin() as conn:
        row = conn.execute(
            text("SELECT key FROM settings WHERE key = :key"),
            {"key": "enabled"},
        ).fetchone()

        if row:
            conn.execute(
                text("""
                    UPDATE settings
                    SET value = :value
                    WHERE key = :key
                """),
                {"value": value, "key": "enabled"},
            )
        else:
            conn.execute(
                text("""
                    INSERT INTO settings(key, value)
                    VALUES(:key, :value)
                """),
                {"key": "enabled", "value": value},
            )


async def copy_with_retry(bot, group_id, source_chat, message_id, post_id):
    max_attempts = 3

    for attempt in range(1, max_attempts + 1):
        try:
            await bot.copy_message(
                chat_id=group_id,
                from_chat_id=source_chat,
                message_id=message_id,
            )
            log_send(group_id, post_id, "success")
            return True

        except RetryAfter as e:
            wait_for = retry_seconds(e.retry_after) + RETRY_EXTRA_SECONDS

            logger.warning(
                "429 RetryAfter | group=%s post=%s attempt=%s wait=%.1fs",
                group_id, post_id, attempt, wait_for
            )

            if attempt >= max_attempts:
                log_send(
                    group_id,
                    post_id,
                    "failed",
                    f"RetryAfter after {attempt} attempts",
                )
                return False

            await asyncio.sleep(wait_for)

        except Forbidden as e:
            log_send(group_id, post_id, "failed", f"Forbidden: {e}")
            return False

        except BadRequest as e:
            log_send(group_id, post_id, "failed", f"BadRequest: {e}")
            return False

        except TelegramError as e:
            if attempt >= max_attempts:
                log_send(group_id, post_id, "failed", f"TelegramError: {e}")
                return False
            await asyncio.sleep(3.0 * attempt)

        except Exception as e:
            logger.exception("Unknown error")
            log_send(group_id, post_id, "failed", f"Unknown: {e}")
            return False

    return False


async def send_all(application: Application):
    if SEND_LOCK.locked():
        return {"sent": 0, "failed": 0, "skipped": True}

    async with SEND_LOCK:
        with engine.begin() as conn:
            groups = conn.execute(
                text("""
                    SELECT chat_id, title
                    FROM target_groups
                    WHERE enabled = 1
                    ORDER BY added_at ASC
                """)
            ).mappings().all()

            posts = conn.execute(
                text("""
                    SELECT id, source_chat, message_id, original_link
                    FROM source_posts
                    WHERE enabled = 1
                    ORDER BY id ASC
                """)
            ).mappings().all()

        if not groups or not posts:
            return {"sent": 0, "failed": 0, "skipped": False}

        sent = 0
        failed = 0

        for group in groups:
            for post in posts:
                source_chat = post["source_chat"]

                if source_chat.lstrip("-").isdigit():
                    source_chat = int(source_chat)

                ok = await copy_with_retry(
                    application.bot,
                    group["chat_id"],
                    source_chat,
                    post["message_id"],
                    post["id"],
                )

                if ok:
                    sent += 1
                else:
                    failed += 1

                await asyncio.sleep(
                    random.uniform(MIN_SEND_DELAY, MAX_SEND_DELAY)
                )

        return {"sent": sent, "failed": failed, "skipped": False}


async def hourly_job(context: ContextTypes.DEFAULT_TYPE):
    if not automatic_enabled():
        return

    result = await send_all(context.application)
    logger.info("자동 발송 결과: %s", result)


async def cmd_send_now(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    if SEND_LOCK.locked():
        await update.effective_message.reply_text(
            "⏳ 이미 발송이 진행 중입니다."
        )
        return

    await update.effective_message.reply_text("📤 전체 발송 시작...")

    result = await send_all(context.application)

    await update.effective_message.reply_text(
        f"✅ 발송 완료\n"
        f"성공: {result['sent']}건\n"
        f"실패: {result['failed']}건"
    )


async def cmd_auto_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    set_automatic(True)
    await update.effective_message.reply_text("✅ 자동 발송을 켰습니다.")


async def cmd_auto_stop(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    set_automatic(False)
    await update.effective_message.reply_text("⏸ 자동 발송을 중지했습니다.")


async def cmd_status(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    with engine.begin() as conn:
        group_count = conn.execute(
            text("""
                SELECT COUNT(*)
                FROM target_groups
                WHERE enabled = 1
            """)
        ).scalar_one()

        post_count = conn.execute(
            text("""
                SELECT COUNT(*)
                FROM source_posts
                WHERE enabled = 1
            """)
        ).scalar_one()

    state = "켜짐" if automatic_enabled() else "꺼짐"

    await update.effective_message.reply_text(
        f"🤖 현재 상태\n"
        f"DB: {DB_KIND}\n"
        f"자동 발송: {state}\n"
        f"주기: {SEND_INTERVAL_SECONDS // 60}분\n"
        f"등록 그룹: {group_count}개\n"
        f"등록 게시물: {post_count}개\n"
        f"발송 간격: {MIN_SEND_DELAY:.1f}~{MAX_SEND_DELAY:.1f}초"
    )


async def cmd_recent_logs(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await admin_guard(update):
        return

    with engine.begin() as conn:
        rows = conn.execute(
            text("""
                SELECT group_id, post_id, status, error_text, created_at
                FROM send_logs
                ORDER BY id DESC
                LIMIT 20
            """)
        ).mappings().all()

    if not rows:
        await update.effective_message.reply_text("아직 발송 로그가 없습니다.")
        return

    lines = ["🧾 최근 발송 로그"]
    for row in rows:
        icon = "✅" if row["status"] == "success" else "❌"
        error = f" | {row['error_text']}" if row["error_text"] else ""
        lines.append(
            f"{icon} G:{row['group_id']} / P:{row['post_id']} "
            f"/ {row['created_at']}{error}"
        )

    text_out = "\n".join(lines)
    if len(text_out) > 3900:
        text_out = text_out[:3900] + "\n..."

    await update.effective_message.reply_text(text_out)


async def post_init(application: Application):
    init_db()

    application.job_queue.run_repeating(
        hourly_job,
        interval=SEND_INTERVAL_SECONDS,
        first=SEND_INTERVAL_SECONDS,
        name="hourly-relay",
    )

    logger.info("봇 시작 | DB=%s", DB_KIND)


def main():
    if not ADMIN_IDS:
        raise RuntimeError("ADMIN_IDS 환경변수를 설정해주세요.")

    app = (
        ApplicationBuilder()
        .token(TOKEN)
        .post_init(post_init)
        .build()
    )

    app.add_handler(CommandHandler(["start", "도움말"], cmd_help))

    app.add_handler(CommandHandler("등록", cmd_add_post))
    app.add_handler(CommandHandler("삭제", cmd_remove_post))
    app.add_handler(CommandHandler("등록목록", cmd_post_list))

    app.add_handler(CommandHandler("방등록", cmd_add_group))
    app.add_handler(CommandHandler("방삭제", cmd_remove_group))
    app.add_handler(CommandHandler("방목록", cmd_group_list))

    app.add_handler(CommandHandler("즉시발송", cmd_send_now))
    app.add_handler(CommandHandler("자동시작", cmd_auto_start))
    app.add_handler(CommandHandler("자동중지", cmd_auto_stop))
    app.add_handler(CommandHandler("상태", cmd_status))
    app.add_handler(CommandHandler("최근로그", cmd_recent_logs))

    app.run_polling(drop_pending_updates=False)


if __name__ == "__main__":
    main()
